language: groovy
dist: trusty
rvm:
- 1.8.8
before_script:
- export VERSION=${TRAVIS_TAG}.${TRAVIS_COMMIT:0:7}
script:
- ant -Dplugin.version=${VERSION}
jdk:
- oraclejdk8
- openjdk7
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  api_key:
    secure: IuHG+MLCSBngsY+mOQSMHA2pPfc2w6a7oCR1tdO7J3CnRy5RyBuCogkYkf5Gyq+1dtK+sStFADtKQRMmTXzA9lgZZxEw9sUByCqUcZ8RdqypZp8aX975GXj6eRItzLwpzIiZFWx6H2fvtboV5f715GlSmgjn7QOu3N4F81Fi53yekm0M0uR/50gyf51r3FwXq08TpPtveQkzQuRHhZ7kp9+g7nmnAnSivqMVB40aifxUvxa0//e8f8DUKgAlGnuVF3eXn+TkEsLHiwNTq5QAz4jmykt2gDFJOQGqKknbBYG0qeYOz/imcHpuWo8/erjxpAZ+86eaxlqqf/ibDpobTFyH4GftTfSngjJ1dzeIWtTskenRvcyGG0mJQoq8JWQDznofZ0LuiHg7s5Z6D2sPWnCqy549qt9bQy87zAUzHrd2pbmvwApq0udPHjZAiR6ofDJhi8ljHibcIbA7gz3jOxuYL9vAfiK3Qj1SFDmbSfBXWkyAmgWkwiy5V1gMVg4jHkkfonTAVANeGrMGCVSb9U8hvpTxD1vq6vVx9Nkb9+5oVywuc1eqjWxa2mX2eKo7kFoRVKV4GM4DUn1SOZtXFOd6agPDfz9Xq1fZtryHTjpx0IYZeiQLVgVX4UdK0QvpRYUMLS6IiQQSd73fcQ7F5Z7Cr8ODTcS7TFlkZclTVD0=
  file_glob: true
  file:
      - dist/datapower-v*.zip
      - dist/dcm.jar
  skip_cleanup: true
  on:
    tags: true
    repo: ibm-datapower/datapower-configuration-manager
